### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by hthabet** [kamerk22/AmazonGiftCode#1]
Hi @kamerk22,

First, thanks for putting this package together. I have a couple of questions: 

1- Do you have tests for this package? I saw there is a reference to `Tests` namespace in `composer.json` but was not able to locate it. 

2- Would you be willing to review PRs If I submit some?

Thanks!

**Comment by kamerk22** [comment]
No there's no Test cases written and you can submit PRs for same. Thank you

**Comment by hthabet** [comment]
ok thanks!
