### ISSUE TITLE
Support for Laravel 9?

### ISSUE THREAD

**Issue by samhaiden** [kamerk22/AmazonGiftCode#10]
Are you planning any support for Laravel 9?

**Comment by goaround** [comment]
I tested it on Laravel 9, works fine. PR: https://github.com/kamerk22/AmazonGiftCode/pull/11

**Comment by samhaiden** [comment]
I just tried a fresh install of Laravel 9 and when trying to require the package it throws an error:

Problem 1
    - kamerk22/amazongiftcode[v1.0.0, ..., v1.0.1] require illuminate/support ~5 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - kamerk22/amazongiftcode 1.0.2 requires illuminate/support ~5|^6.0|^7.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - kamerk22/amazongiftcode v1.0.3 requires illuminate/support ~5|^6.0|^7.0|^8.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires kamerk22/amazongiftcode ^1.0 -> satisfiable by kamerk22/amazongiftcode[v1.0.0, v1.0.1, 1.0.2, v1.0.3].

**Comment by samhaiden** [comment]
Thanks!
